### ISSUE TITLE
[Bug] Wrong process is selected when filtered

### ISSUE THREAD

**Issue by techygrrrl** [savannahostrowski/gruyere#10]
This app works well for viewing ports. Unfortunately I wasn't able to kill the process. It looks like the wrong port gets killed. I'm on macOS.

I'm not sure what's going but this is the output:

```text

╭──────────────────────────────────────────────────────╮
│                                                      │
│    Are you sure you want to kill port Port :8081     │
│                       (81756)?                       │
│                                                      │
│             Yes        No, take me back              │
│                                                      │
╰──────────────────────────────────────────────────────╯


2023/05/01 21:47:12 FATA error Killing process: 72800 (int value = 72800)
```

When I run greyere, I notice the first item is pid 72800 so I don't know if navigating is working correctly while filtering. This is visible in the first split second of the GIF.

Also, when I go through my lengthy list of processes and find the one I want to kill (port 8081 with pid 81756), when I hit enter, it logs the correct pid.

So the bug looks like it occurs only when filtering.

![gruyere kills random port](https://user-images.githubusercontent.com/88961088/235583497-979934c7-3c10-4029-aa73-ea56faac9d12.gif)

This is some code I added for logging. I also added a test to see if I can kill processes on my machine from Go and it works: https://github.com/savannahostrowski/gruyere/compare/main...techygrrrl:gruyere:bug-wrong-pid

**Comment by savannahostrowski** [comment]
I believe that this is now resolved via  #12.
