### ISSUE TITLE
Test mouse navigation on WSL

### ISSUE THREAD

**Issue by savannahostrowski** [savannahostrowski/gruyere#26]
I was seeing some sporadic issues where ports weren't clickable. I can't reliably repro.

Mousewheel scroll and button click on the confirmation screen seem to be functioning correctly.

**Comment by whoop-t** [comment]
Just to note, Zone requires bubbletea to be fullscreen. When working on adding the mouse support, I noticed there would be issues with the click hitbox if say you start up gruyere in too small of a terminal window and things are cut off or resize to window too small with stuff cut off.

Example: If you have your terminal to a really small size where say the header or some portions of gruyere get cut off, this will mess up the Zone marks(the click portion) and the clickable portion wont line up

This may have something to due with it, tho it might require refactoring how resizing is handled. The list size is hard coded currently but may be better to refactor to make it dynamic along with the title

**Comment by savannahostrowski** [comment]
Closing for now as I cannot repro
