### ISSUE TITLE
Faster ports updates

### ISSUE THREAD

**Issue by VasilyKaiser** [savannahostrowski/gruyere#8]
Running cmd could take time and it's blocking whole app.

**Comment by savannahostrowski** [comment]
Do you have an example of this happening or is this speculative?

**Comment by VasilyKaiser** [comment]
I thought it was obvious, but I see now no difference on Linux box, sorry. 
Perhaps it is an issue only on Windows, because of lack of tool such as `lsof`, to get processes fast.

**Comment by savannahostrowski** [comment]
No worries - I'm going to close this for now in favour of #6 as I think that, in general, Windows will need some further consideration.
